### ISSUE TITLE
apt-get update on beta 6 ISO results in NO_PUBKEY 6A72C389B517460F

### ISSUE THREAD

**Issue by wd5m** [AllStarLink/ASL-Live-Build#21]
I have installed the beta 6 ISO on a Vultr VPS.  When I run "apt-get update" I get errors about NOPUBKEY.

> apt-get update
> Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
> Get:2 http://apt.allstarlink.org/repos/asl_builds buster InRelease [7,392 B]
> Hit:3 http://deb.debian.org/debian buster InRelease
> Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
> Err:2 http://apt.allstarlink.org/repos/asl_builds buster InRelease
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A72C389B517460F
> Fetched 125 kB in 0s (280 kB/s)
> Reading package lists... Done
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.allstarlink.org/repos/asl_builds buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A72C389B517460F
> W: Failed to fetch http://apt.allstarlink.org/repos/asl_builds/dists/buster/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A72C389B517460F
> W: Some index files failed to download. They have been ignored, or old ones used instead.

David M.
WD5M

**Comment by robvella** [comment]
Hi David --

Here's the fix:

```
curl -s http://apt.allstarlink.org/repos/repo_signing.key | sudo apt-key add -
apt update
```

**Comment by ke5gdb** [comment]
Rob,

The instructions at https://wiki.allstarlink.org/wiki/Downloads contain a link to a key that returns a 404 error. Can you update that page to reflect your new link here?

73 de KE5GDB
