### ISSUE TITLE
3 bugs

### ISSUE THREAD

**Issue by KenHorse** [AllStarLink/ASL-Live-Build#23]
Tried new beta image. 3 issues

    Raspi-config won’t assign any other user then Pi. I logged in as root to run it (not su’d, logged in)

    LAN connected being forced to static IP of 169.254.35.57 even after running asl-menu to select DHCP and rebooting

    Receive “Can’t communicate with wpa_supplicant” despite fact that I created a correct /etc/wpa_supplicant/wpa_supplicant.conf. Also, the binary does exist in /usr/sbin

These issues are identical on a Pi3+ and Pi4

**Comment by robvella** [comment]
Closed via community.
