### ISSUE TITLE
Unable to connect to remote asterisk (does /var/run/asterisk.ctl exist?)

### ISSUE THREAD

**Issue by firealarmss** [AllStarLink/ASL-Live-Build#34]
**Describe the bug**
This has happened every instance of ASL that isnt on a pi 
This happens when trying to use asterisk
Unable to connect to remote asterisk (does /var/run/asterisk.ctl exist?)

**Comment by davidgsd** [comment]
Saw this same issue, as an experiment I tried installing ASL on Mint and then Debian 11 (downloading and compiling the latest source from github). In both cases (after a couple errors that were easy enough to resolve) the configure, make and make install all completed with no errors. But the make install does not seem to actually copy some of the files where they need to be or set up asterisk to run as a service. If I run asterisk from the command line it was giving error that couldn't find a /dev/dahdi/ directory.
