### ISSUE TITLE
Invalid command in /etc/network/if-up.d/firewall causes networking service to exit

### ISSUE THREAD

**Issue by davidgsd** [AllStarLink/ASL-Live-Build#40]
I have 3 different nodes I regularly use and test on noticed on 2 of them had the same issue, that after the DHCP lease expired (after being on for about 1 day) it would fail to renew and the node would lose networking connectivity. I posted the Debian forums for advice on debugging the issue (https://forums.debian.net/viewtopic.php?t=153760) and found that an invalid command in /etc/network/if-up.d/firewall -- "iptables-restore < /etc/iptables.conf" was causing the networking service to exit with an error.

Both nodes are Dell Wyse 3040 thin-clients.  One is running AllStarLink Asterisk Version 2.0.0-beta 03/24/2021 GIT 6a9b0c6.  And the other is running even newer code I compiled from source. To get the latest code and some PRs that looked like they might be helpful I did the following:
```
git clone git@github.com:AllStarLink/ASL-Asterisk.git ASL-with-PRs
cd ASL-with-PRs/
git pull origin pull/34/head
git pull origin pull/41/head
git pull origin pull/42/head
```
Then compiled & installed. This fixed some stats segfault error messages that were cluttering the syslog but made no difference to the networking issue.

After commenting out the offending line in /etc/network/if-up.d/firewall: "iptables-restore < /etc/iptables.conf" the issue is fixed and the node ran for at least several days continuously with no networking issues.

A 'sudo service networking status' now shows the service is active and working fine. Whereas before it would show:
```
networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2023-01-25 21:40:20 PST; 7min ago
     Docs: man:interfaces(5)
  Process: 364 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
 Main PID: 364 (code=exited, status=1/FAILURE)

Jan 25 21:40:20 NODE571571 systemd[1]: Starting Raise network interfaces...
Jan 25 21:40:20 NODE571571 ifup[364]: /etc/network/if-up.d/firewall: 2: /etc/network/if-up.d/firewall: cannot open
Jan 25 21:40:20 NODE571571 ifup[364]: run-parts: /etc/network/if-up.d/firewall exited with return code 2
Jan 25 21:40:20 NODE571571 ifup[364]: ifup: failed to bring up lo
Jan 25 21:40:20 NODE571571 ifup[364]: /etc/network/if-up.d/firewall: 2: /etc/network/if-up.d/firewall: cannot open
Jan 25 21:40:20 NODE571571 ifup[364]: run-parts: /etc/network/if-up.d/firewall exited with return code 2
Jan 25 21:40:20 NODE571571 ifup[364]: ifup: post-up script failed
Jan 25 21:40:20 NODE571571 systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 21:40:20 NODE571571 systemd[1]: networking.service: Failed with result 'exit-code'.
Jan 25 21:40:20 NODE571571 systemd[1]: Failed to start Raise network interfaces.
```

Error message from syslog:
`Jan 25 21:40:20 NODE571571 ifup[364]: /etc/network/if-up.d/firewall: 2: /etc/network/if-up.d/firewall: cannot open  /etc/iptables.conf: No such file`

I do have iptables firewall enabled on both nodes, ie.
```
sudo iptables -S
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N fail2ban-asterisk-tcp
-N fail2ban-ssh
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 192.168.0.0/16 -j ACCEPT
-A INPUT -s 10.0.0.0/24 -j ACCEPT
-A INPUT -s 172.16.0.0/20 -j ACCEPT
-A INPUT -p tcp -j fail2ban-asterisk-tcp
-A INPUT -p tcp -j fail2ban-ssh
-A INPUT -p udp -m udp --dport 4569 -j ACCEPT
-A INPUT -p udp -m udp --dport 5038 -j ACCEPT
-A INPUT -p udp -m udp --dport 5198 -j ACCEPT
-A INPUT -p udp -m udp --dport 5199 -j ACCEPT
-A INPUT -p udp -m udp --dport 667 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 4569 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5200 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5038 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 667 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -j REJECT --reject-with icmp-port-unreachable
-A fail2ban-asterisk-tcp -j RETURN
-A fail2ban-ssh -j RETURN
```
Thus it seems iptables is working fine, and apparently does not use a "/etc/iptables.conf" file.

Let me know if I can provide any other info.

Thanks,
David

**Comment by tsawyer** [comment]
Sounds like this happen upstream. Is there a update from Debian and if so could you post it here, please?

**Comment by davidgsd** [comment]
From my post on the debian forum it did not sound like anyone had heard of the issue before (one person stated "AFAIK this file [/etc/network/if-up.d/firewall] is not part of a standard Debian installation"), and my prior searches turned up no similar issue, so I don't know where the bug might have been introduced originally. Seems that could take some significant investigation. Hopefully someone who is more familiar with the build process / integration timeline of debian + asterisk or the history of this particular file can help narrow that down. Otherwise though things work fine without the file, which has only one line referencing the non-existent /etc/iptables.conf file.
