### ISSUE TITLE
asl-asterisk dependencies unmet - Debian 11.6 

### ISSUE THREAD

**Issue by FJRPilot** [AllStarLink/ASL-Live-Build#41]
**Describe the bug**
When following the instructions to install the ASL on a new install of Debian Linux (using the ASL Repository method),  I get a system notification that "some Packages could not be installed".

The following packages have unmet dependencies:
 asl-asterisk : Depends: libsnmp30 (>= 5.7.3+dfsg) but it is not installable
                Depends: libsqlite0 (>= 2.8.17) but it is not installable
**E: Unable to correct problems, you have held broken packages.**
root@AllStar:/tmp#

**To Reproduce**

1. execute a clean install of Debian 11.6.
2. Follow the instructions to install asl-asterisk from the ASL Repository
3. Execute the commands in order and when you come to the step to install "asl-asterisk" you will get the error noted,

**Expected behavior**
I expect the "asl-asterisk" component to install correctly and without errors to allow me to execute the next required instructions.

**Screenshots**

**Additional context**
![Screenshot from 2023-04-23 18-47-49](https://user-images.githubusercontent.com/35666213/233876673-f5cfabb0-0b78-47f1-98b9-f97c9f404a66.png)

**Comment by pcpackrat** [comment]
Looks like Debian 10 only still.  I just installed 12 and then 11 and got the same errors.

**Comment by tsawyer** [comment]
> @ajpaul25 Says; This is what happens when you try to install packages made for 10 on either 11 or 12 and the libraries have been changed upstream.

I'll update the WiKi.
