### ISSUE TITLE
ASL 2.0 B6 Send Node Status

### ISSUE THREAD

**Issue by dmkacz** [AllStarLink/ASL-Live-Build#43]
Was getting many node status reporting errors in both Asterisk and Linux kernel logs. Tracked to status reporting problem (defined in rpt.conf) and noted that script send_node_status.sh and sub-directory /etc/asterisk/local do not exist from the default install.

Temporary work around is to comment out the two lines "statpost_program and statpost url in rpt.conf in both both node configurations. But of course at the expense of Allstar Link not getting your node statistics.

Has this script been written for 2.0 and just not get installed for some reason, or it a work in progress in the beta?

**Comment by tsawyer** [comment]
That script and sub-directory are not part of any ASL distro. You must have picked that up somewhere else.
