### ISSUE TITLE
Will you create an orange pi port

### ISSUE THREAD

**Issue by fjb59** [AllStarLink/ASL-Live-Build#44]
**Describe the bug**
this won;t build on an orange pi 3. i suspect the architecture is w

**To Reproduce**
1. Go to '.your install page'
3. 'whien you try in install the headers uname -r fails. that's resolvable by just installing the latest headers. however afte it fails because the architecture is wrong. 
4. please do a port for the orange pi and the banana pi. as if there is another shortage of raspberri pi's we don't want to be helf hostage for prices.

**Comment by tsawyer** [comment]
There is a Pi5 coming. You can preorder it on a number of sites. I have one on order. 

I suspect ASL will support the Pi5. Hard to say about the other fruits. We are quietly working on a new version of ASL. Stand by for details much later.

**Comment by fjb59** [comment]
i found your source files and tried building from source. it it had dahdi issues (unsupported architecture) and a dhahdi include file was missing. i'm wandering if that was due to the failed dummy driver build.
i current;y have no plans to get an rpi5 it uses 25 watts which means standard rpi psu will not run it. however your software worked just find and an rpi 3. however it would be a massive boost if we could work it on other fruits.. i have an orangepi lt33 that would suit it perfectly.
