### ISSUE TITLE
Documentation: Arm64 not supported

### ISSUE THREAD

**Issue by lbussy** [AllStarLink/ASL-Live-Build#46]
**Describe the bug**
When I use a fresh 64-bit Bookwork image and attempt to install from the ASL repository, I see that 64-bit is not supported:

```
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://apt.allstarlink.org/repos/asl_builds buster InRelease' doesn't support architecture 'arm64'
```

**Expected behavior**
I would suggest updating the documentation to include this restriction, or add Arm64 binaries.

**Comment by ve3ebc** [comment]
I think for the image you are installing you mean Bookworm and not Bookwork. I am having the same problem. Rpi 5 for me is not accepting an ASL install with the instructions provided and is throwing the error you describe. I also tried the beta for pi 4 but it looks like the Rpi 5 bootloader insists on installing Bookworm.
