### ISSUE TITLE
Some packages could not be installed

### ISSUE THREAD

**Issue by rcleroy** [AllStarLink/ASL-Live-Build#47]
**Describe the bug**
me packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 asl-asterisk : Depends: libsnmp30 (>= 5.7.3+dfsg) but it is not installable
                Depends: libsqlite0 (>= 2.8.17) but it is not installable
                Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Expected behavior**

**Screenshots**

**Additional context**
I did a complete fresh install of Debian before installing the ASL repositories files.  I am probably missing something but when I get to the step:
apt -y install asl-asterisk   
things start to go off tracks at that point.  
Im sure its a simple thing that I have missed.  Any guidance would be really appreciatedl
Regards  Rob

**Comment by tsawyer** [comment]
We are recommending another way to install Allstar for now. Do another fresh install of Debian 12 then use this procedure:
https://community.allstarlink.org/t/awia-another-way-to-install-asl2-beta/20711

**Comment by tsawyer** [comment]
Let us know on Community if needed.
