### ISSUE TITLE
asl Asterisk 

### ISSUE THREAD

**Issue by N7UQ** [AllStarLink/ASL-Live-Build#51]
The following packages have unmet dependencies:
 asl-asterisk : Depends: libsnmp30 (>= 5.7.3+dfsg) but it is not installable
                Depends: libsqlite0 (>= 2.8.17) but it is not installable
                Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by martin3dsc** [comment]
New to asl and I started Install ASL

Rpi 3B  Bookworm

Next as root (or with sudo) run the following commands to install ASL. 
/tmp# apt -y install asl-asterisk
result :
The following packages have unmet dependencies:
 asl-asterisk : Depends: libsnmp30 (>= 5.7.3+dfsg) but it is not installable
E: Unable to correct problems, you have held broken packages.
